name: Sedstart QA

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SedStart test run
        uses: sedstart/runcloud@v1
        with:
          api_key: ${{ secrets.SEDSTART_API_KEY_QA }}
          project_id: 459
          test_id: 2136
          profile_id: 945
          browser: chrome
          headless: false
          environment: QA
