name: Sedstart QA

on:
  workflow_dispatch:

jobs:
  sedstart-run:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SedStart test run
        uses: sedstart/runcloud@v1
        with:
          api_key: ${{ secrets.API_Key }}
          project_id: 270
          test_id: 1186
          profile_id: 330
          browser: chrome
          headless: false
